### ISSUE TITLE
2FA broken view

### ISSUE THREAD

**Issue by renege** [thedevdojo/auth#104]
Hi,
This is the output of `/user/two-factor-authentication`

<img width="461" alt="Scherm­afbeelding 2024-07-25 om 16 33 02" src="https://github.com/user-attachments/assets/b960cd1d-256f-4977-87df-953142843d24">
<img width="459" alt="Scherm­afbeelding 2024-07-25 om 16 33 09" src="https://github.com/user-attachments/assets/32f6a994-7b71-43f2-ad86-58cf5f2fd19e">

Not like it should be I guess. What is wrong?

**Comment by skdishansachin** [comment]
Can you share your operating system, web browser, and version?

**Comment by renege** [comment]
@skdishansachin 
I don’t know how this will help, but it’s on both iOS and macOS. Tried Safari and Chrome. 
All on latest versions. 

Looks to me more some rendering issues. Related to 2FA. All other Auth views show properly.

**Comment by skdishansachin** [comment]
This is wired. You tried running the `php artisan view:clear`

**Comment by renege** [comment]
Yes. Not helped.

**Comment by skdishansachin** [comment]
Hey, could you share any console logs and Laravel logs that you think might be helpful?

**Comment by renege** [comment]
Both no errors. Just rendering of the view failed.

**Comment by tnylea** [comment]
Yes, if you are getting a view like this you must run `php artisan view:clear`.

This is an issue with Laravel Volt or Laravel folio.

I'll be sure to add this info in the documentation and perhaps I can do a PR to Folio or Volt to fix this issue.

Thanks!
