### ISSUE TITLE
GitHub Login Error The redirect_uri is not associated with this application

### ISSUE THREAD

**Issue by dayas-kr-coder** [thedevdojo/auth#120]
## Issue Description
When logging in via GitHub, the following error occurs:
```
The redirect_uri is not associated with this application
```

## Steps to Reproduce
1. Set up a Laravel app with GitHub OAuth.
2. Attempt to log in using GitHub.
3. Encounter the error.

## Possible Cause
The redirect URI may be misconfigured.

### GitHub Developer Settings
- **Authorization callback URL**:
  ```
  http://devdojo.test/sign-in/github/redirect
  ```

### Laravel `.env` File
- `APP_URL`:
  ```env
  APP_URL=http://devdojo.test
  ```

## Troubleshooting
1. Verified GitHub's `Authorization callback URL` matches Laravel's redirect URI.
2. Confirmed `APP_URL` in the `.env` file is correct.
3. Checked redirect URI configuration in Laravel settings.

## Additional Information
- Error persists despite configuration checks and clearing Laravel’s cache.

## Request for Assistance
Could you help identify any potential misconfigurations or missing steps? Guidance on resolving the redirect URI mismatch would be appreciated.

**Comment by skdishansachin** [comment]
I think the issue might be with your **Authorization callback URL**. It needs to be `http://devdojo.test/auth/github/callback` instead.

**Comment by tnylea** [comment]
@dayas-kr-coder Let us know if this issue has been resolved. Closing for now ;)

Thanks!
