### ISSUE TITLE
Class to enable and disable the 2FA

### ISSUE THREAD

**Issue by itsmejyv** [thedevdojo/auth#122]
Hi dev!

I would like to request a class for view where we can disable and enable it without using the jetstream. so we can integrate it to the custom profile setting.

**Comment by tnylea** [comment]
Hey @itsmejyv Thanks for the suggestion. Can you please clarify what you mean by this. Additionally we are going to be closing issues here and are requesting that users submit issues and suggestions here: https://devdojo.com/questions.

Thanks so much!
