### ISSUE TITLE
Add Support for Passkeys for Authentication

### ISSUE THREAD

**Issue by tygoegmond** [thedevdojo/auth#42]
I would love to see support for passkeys integrated into this library. Passkeys are becoming the new standard for authentication, providing a more secure and user-friendly alternative to traditional passwords.

Benefits of Passkeys:
- **Enhanced Security:** Passkeys are resistant to phishing attacks, credential stuffing, and other common password-related security issues.
- **User Convenience:** Passkeys simplify the user experience by eliminating the need to remember and manage complex passwords.

**Comment by tnylea** [comment]
Thanks for the issue, but this might be out of scope for this package. Can you give me the full flow of how a Passkey authentication would function.

**Comment by tnylea** [comment]
Closing for now, but if you want to open a PR for this functionality. I'm totally open to review it.

Thanks!
