### ISSUE TITLE
Missing setup.checkbox-row component

### ISSUE THREAD

**Issue by tygoegmond** [thedevdojo/auth#44]
Currently `php artisan view:cache` will fail since the `auth::setup.checkbox-row` component is missing.

**Comment by tnylea** [comment]
Thanks for pointing this out. I'll get this updated soon and publish a new release 😉

**Comment by tnylea** [comment]
Submitting a new release tomorrow that will resolve this issue. Thanks again!

**Comment by tnylea** [comment]
@tygoegmond This has been resolved in the latest release 1.0.2 https://github.com/thedevdojo/auth/releases/tag/1.0.2. Thanks for pointing this out 😉
