### ISSUE TITLE
Enable Multi-language

### ISSUE THREAD

**Issue by a-zog** [thedevdojo/auth#45]
Congrats on the launch, great package !
Would be great to add multiple translations for each page/copy.
Thank you again

**Comment by a-zog** [comment]
Great, thanks !
Would it be also possible to support custom routing for multi-lang usage? (by enabling a quick combination with https://github.com/codezero-be/laravel-localized-routes for example)

**Comment by tnylea** [comment]
I'm sure there's probably a way to utilize this package with the Auth package, if you find a good solution that would work well as a PR, I'm totally open for reviewing it.

For now I'm going to close this issue, but if you open a PR feel free to let me know.

Thanks.
