### ISSUE TITLE
Add custom fields for registration

### ISSUE THREAD

**Issue by Matse2005** [thedevdojo/auth#46]
In my project I require my users to fill in there firstname, lastname and an username. I was thinking about adding this package but I still need those fields to be filled it. Is there a way this can be added and also add custom validation?

**Comment by tnylea** [comment]
Yeah, I'm totally open for integrating custom fields on the login/registration pages. Can you provide me with an outline of how this might be implemented in the package. How would you foresee this being an ideal way to add custom fields on the registration form along with validation rules for those custom fields?

Let me know 😉

**Comment by bilogic** [comment]
I was thinking about how this might be achieved, and it might be simpler to just have callbacks in code. I think a UI will involve alot of code yet still unable to meet the aim of custom fields, imagine if someone needs birthdate during registration.

Another approach might be to create the account first, and rely on another package e.g. profile to fill in those custom fields. This way, this package remains focused and simple: verify that the user knows his/her password.

**Comment by IsaacHatilima** [comment]
> I was thinking about how this might be achieved, and it might be simpler to just have callbacks in code. I think a UI will involve alot of code (bloat this package) yet still unable to meet the aim of custom fields, imagine if someone needs birthdate during registration.
> 
> Another approach might be to create the account first, and rely on another package e.g. profile to fill in those custom fields. This way, this package remains focused and simple: verify that the user knows his/her password and the paths leading to it.

With this line of thought then the name field should be removed and just register with email and password. The name and other details should then be provided after successful registration. That way, the user isn't given an extra step even though small of having to separate the first and last name if the implementation dictates that.

**Comment by tnylea** [comment]
Yeah, I like all these suggestions and I do agree that it would work best if we were to let another package provide that additional functionality. That would be kind of like an onboarding step.

@IsaacHatilima Totally hear what you are saying about the Name. I think that we'll keep it in there for now; however, if someone wanted to have a second step where the user added First Name, Last Name, Birthdate, etc. then they could just disable adding name field as part of the registration.

I'm going to close this for now, but I'll be sure to keep considering how we can add custom fields for registration. Perhaps there will be another package soon :)

**Comment by BoweFrankema** [comment]
Hi @tnylea I was just wondering if there is an update on this? Maybe that super secret Profile package you were teasing? I'd love to see this for sure <3
