### ISSUE TITLE
Not very performant on Windows 11?

### ISSUE THREAD

**Issue by everonegraham** [thedevdojo/auth#47]
Hi there, amazing project.

Just came across it and giving it a run, but it doesn't seem very performant on Windows 11?

Tested with both a fresh Laravel project and an already created project. 

The example image below is me going from the login page to the signup page only.

![image](https://github.com/thedevdojo/auth/assets/28059522/a33bb533-ba30-4598-8161-be433fa057cc)

Please let me know what other information you may need to help with this.

**Comment by everonegraham** [comment]
Correct, it is a local install.

**Comment by tnylea** [comment]
That's interesting. I wonder why those pages would take so long to load. Does this happen with any other routes in your application? Are you using Herd?

**Comment by everonegraham** [comment]
Reporting back,

So it is much better when using herd. I was running the `aritsan serve` and `npm run dev` from the terminal in VSCode. Unclear if that's where the issue is stemming from.

**Comment by tnylea** [comment]
Ok, if that's happening in the entire application, it seems like it's an issue with the local setup as opposed to just this app, so I'm going to close this issue, but feel free to re-open if you think this issue is rooted from this package.

Thanks.
