### ISSUE TITLE
Set up routes for auth pages?

### ISSUE THREAD

**Issue by everonegraham** [thedevdojo/auth#48]
Hi there,

I've been trying to see what the best way to handle routes to the auth pages from my test app. 

What are suggested ways to do this cleanly? Using href="/auth/login” and `Route::redirect('/login', '/auth/login');` in the route.web but doesn't seem to work as intended for me. Rather than going to the route and opening the page, it simply opens on the home page like an overlay?

**Comment by tnylea** [comment]
Hey there,

so, you are trying to add a redirect from `/login' to the `/auth/login` page? This should already be provided as default functionality in this package. Let me know if that's what you were referring to, and how I can try and replicate what you are trying to do.

Thanks!

**Comment by everonegraham** [comment]
Hey, thanks for responding promptly.

It didn't work for me out of the box. I had to append the auth/login etc to the url manually. 

I'm about to start a fresh project just to make I didn't mess something up along the way.

**Comment by everonegraham** [comment]
Reporting back,

It seems to be working in the fresh installation. But it seems to open in an overlay type way when going from a login button.

Please refer to the image below for an example.

![image](https://github.com/thedevdojo/auth/assets/28059522/cc665c9a-fd03-4b9b-afd7-562406824ed6)

In the back, you can see where the default home page for a fresh Laravel (Inertia/react) install is.

**Comment by tnylea** [comment]
Ok, let me try and debug this a little further and see if I can replicate this functionality and get it fixed 😉

**Comment by everonegraham** [comment]
Awesome, please let me know if you need anything else. :D

**Comment by tnylea** [comment]
Ok, Just responded with a solution in this issue here: https://github.com/thedevdojo/auth/issues/49.

Thanks for helping to resolve these issues 😉

Hope you have a great day.
