### ISSUE TITLE
Incorrect Client_ID Format Sent by FACEBOOK Provider

### ISSUE THREAD

**Issue by neosign** [thedevdojo/auth#50]
The FACEBOOK provider is sending the Client_ID in an incorrect format. Specifically, the Client_ID is being sent as 1.18xxxxxxxxxxxxE+15 in the client_id parameter instead of a proper numeric value.

Steps to Reproduce
Attempt to use the FACEBOOK provider with a valid Client_ID.
Observe the Client_ID sent in the client_id parameter in the URL.
Expected Behavior
The Client_ID should be sent as a valid numeric parameter.

Actual Behavior
The Client_ID is sent as 1.18xxxxxxxxxxxxE+15, which is not recognized as a valid app ID by Facebook.

Error Messages
Facebook Browser Error
_The provided app ID does not look like a valid app ID._

Then I fixed the client_id and see  another Laravel Callback Error
When attempting a server-to-fb API callback, the following error is encountered:

_Missing or invalid client id.,"type":"OAuthException","code":101_

Environment
Version: laravel 11 with breeze installed
Platform: Ubuntu

**Comment by BnodpriA** [comment]
@neosign I am also facing the same problem, The same client ID and client secret are working when I am using custom facebook login feature using socialite in laravel breeze in react inertia

**Comment by tnylea** [comment]
Possible new update going out tomorrow that might resolve this. I'll keep you posted. If not, I'll debug further.

Thanks.

**Comment by tnylea** [comment]
@neosign Can you check if this latest update resolves your issue. A new version 1.0.2 has been tagged: https://github.com/thedevdojo/auth/releases/tag/1.0.2.

Keep me posted. Thanks.

**Comment by BnodpriA** [comment]
@tnylea I updated the composer and tried to check if the login issue has been fixed but it doesn't seem to be fixed even after changing `config/devdojo/auth/language.php` file
![Screenshot from 2024-06-23 21-08-57](https://github.com/thedevdojo/auth/assets/19488490/71755de6-e4ff-4fe7-a361-26017aaf25c0)

**Comment by neosign** [comment]
> @neosign Can you check if this latest update resolves your issue. A new version 1.0.2 has been tagged: https://github.com/thedevdojo/auth/releases/tag/1.0.2.
> 
> Keep me posted. Thanks.

I just tried version 1.0.2 this morning, and it doesn't seem to be working.

**Comment by neosign** [comment]
1.0.2 still has error 
I got a dirty fix,  not super clean but workable lol (while waiting for real fix.)
/vendor/devdojo/auth/src/Http/Controllers/SocialController.php 
`  private function dynamicallySetSocialProviderCredentials($provider)
    {
        $socialProvider = SocialProvider::where('slug', $provider)->first();
       
        **if ($provider=="facebook"){
            $socialProvider->client_id = sprintf("%d", $socialProvider->client_id);
        };**

        Config::set('services.'.$provider.'.client_id', $socialProvider->client_id);
        Config::set('services.'.$provider.'.client_secret', $socialProvider->client_secret);
        Config::set('services.'.$provider.'.redirect', '/auth/'.$provider.'/callback');

    }`

**Comment by BnodpriA** [comment]
@neosign  It works for me as well. I hope fix for this issue will be included in newer version

**Comment by tnylea** [comment]
Thanks for the updates. I'll be submitting a PR for this fix shortly 👍

**Comment by tnylea** [comment]
I've just added this fix in the latest 1.0.3. I've also added another method in the SocialAuthController that will help with any other edgecases similar to this for other networks. 

Thanks and let me know if you have any other issues.
