### ISSUE TITLE
Error saving on social_provider_user table after Google Login

### ISSUE THREAD

**Issue by RudyAnconi** [thedevdojo/auth#51]
Devdojo\Auth\Http\Controllers\SocialController@callback is giving me a error:

`SQLSTATE[42703]: Undefined column: 7 ERROR: colunmn "id" doesn't exists LINE 1: ..., $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) returning "id" ^ (Connection: pgsql, SQL: insert into "social_provider_user" ("provider_user_id", "nickname", "name", "email", "avatar", "provider_data", "token", "refresh_token", "token_expires_at", "provider_slug", "user_id", "updated_at", "created_at") values (XXXXXX, ?, XXXXXXXX, XXXXXX@gmail.com, https://lh3.googleusercontent.com/a/XXXXXXX"{\"sub\":\"XXXXXXX\",\"name\":\"XXXXXXX\",\"given_name\":\"XXXXXX\",\"family_name\":\"XXXXXX\",\"picture\":\"https:\\\/\\\/lh3.googleusercontent.com\\\/a\\\/XXXXXXXc\",\"email\":\"XXXXXXX@gmail.com\",\"email_verified\":true,\"id\":\"XXXXXXXXXXXXX\",\"verified_email\":true,\"link\":null}", XXXXXXX, ?, 2024-06-21 21:07:26, google, 1, 2024-06-21 20:07:27, 2024-06-21 20:07:27) returning "id")`

I belive it's line 67:
$newUser->addOrUpdateSocialProviderUser(...);

I just created a new project, installed the devdojo auth following the guide, runed the migrations and added the Google Keys on .env. Same error.

After looking the table social_provider_user, the structure doesn't contains the column "key" to return. The migration doesn't add it as well. The primary key is `$table->primary(['user_id', 'provider_slug']);`.

Now, why the parsed query from the ORM results on a `return "id"` at the end, I don't know. Driver maybe? PostgreSQL falt? How do we fix it?

Windows 11, PHP 8.3.8, PostgreSQL 16.2 running `php artisan serve`.

**Comment by RudyAnconi** [comment]
I've added on the model SocialProviderUser.php 
`protected $primaryKey = ['user_id', 'provider_slug'];
public $incrementing = false;`.

Now it's writing on the table. 

My next error is: 
`SQLSTATE[42703]: Undefined column: 7 ERROR: column "0" doesn't exists LINE 1: select * from "users" where ("0" = $1 and "1" = $2) limit 1 ^ (Connection: pgsql, SQL: select * from "users" where ("0" = user_id and "1" = provider_slug) limit 1)`.

Investigating.

**Comment by RudyAnconi** [comment]
Well, I don't understand now.

The cookie is being saved.

The SessionGuard.php file is getting the $id fine:
`$id = $this->session->get($this->getName());`

But on the next line, when `$this->user = $this->provider->retrieveById($id)` tries to get the user we have this weird query `select * from "users" where ("0" = user_id and "1" = provider_slug) limit 1`

**Comment by A-Moussa0** [comment]
I am running into the same exact situation, I didn't do any of the extra steps @RudyAnconi did though.

I am using Supabase (postgres)

**Comment by RudyAnconi** [comment]
The fix that I suggested only solve half of the problem.

I'm still having problems with the `$this->user = $this->provider->retrieveById($id)`

**Comment by RudyAnconi** [comment]
After restart the server and delete the session, now it's working 👍

**Comment by tnylea** [comment]
Thanks @RudyAnconi, does this PR that you submitted resolve the issue you were experiencing: https://github.com/thedevdojo/auth/pull/55/files. If so, I'll be sure to tag a new release tomorrow. I have a few more updates that will be going into that release as well.

**Comment by RudyAnconi** [comment]
@tnylea Yes, the PR solve the problem. Thank you for the quick follow up.

**Comment by tnylea** [comment]
Perfect! Just tagged a new release here: https://github.com/thedevdojo/auth/releases/tag/1.0.2. Appreciate the help with that PR 😉

Feel free to let me know if there are any other issues or if you have any additional PR's you want to contribute.

Thanks! Talk to you soon.
