### ISSUE TITLE
2FA validation

### ISSUE THREAD

**Issue by divdax** [thedevdojo/auth#52]
Submitted a wrong code:
<img width="1539" alt="image" src="https://github.com/thedevdojo/auth/assets/1456739/0cb97cf3-97ce-4259-a977-0072e96c2209">

**Comment by tnylea** [comment]
Can you check your `composer.lock` file and see which version of Auth you have installed. This message should not be in the latest version. 

I've searched the codebase for that error in the latest release and on main and I'm not seeing it in there.

You should be able to search your `composer.lock` for `devdojo/auth` and see which version is installed. LMK. Thanks!

**Comment by tnylea** [comment]
Let me know which version this is. I'm really interested in figuring out how you got that message and which version you're seeing that in. Thanks.

**Comment by tnylea** [comment]
@divdax I'm closing this issue for now, but if you can check that version and get back to me if this is still happening in the latest version we can re-open.

Thanks!
