### ISSUE TITLE
Invalid Request Body Parameters Tiktok

### ISSUE THREAD

**Issue by khfiii** [thedevdojo/auth#57]
Failed to log in with TikTok because the request body parameter requires a client key, but client id given.

https://developers.tiktok.com/doc/client-access-token-management/
![image](https://github.com/thedevdojo/auth/assets/140385148/8a559952-9c1c-4f5a-9de1-1f9c6d6c4053)

When i tryna to die and debug
![image](https://github.com/thedevdojo/auth/assets/140385148/31f3ce83-b38e-485d-a121-22a2ad6d79d2)

**Comment by tnylea** [comment]
We're going to be tagging a new version tomorrow that may resolve this. I'll keep you posted. If it does not resolve this we'll investigate further 😉

**Comment by khfiii** [comment]
Wow that's really awesome, I thank the team who made this package, it really saves time. I really apreciate it.

**Comment by tnylea** [comment]
Ok, can you go ahead and try with the latest release 1.0.2 https://github.com/thedevdojo/auth/releases/tag/1.0.2.

If not, keep me posted and we'll try and replicate this issue and get it resolved 😊 Thanks!

**Comment by tnylea** [comment]
Closing for now, but let me know if you've gotten it working with 1.0.3

Thanks!
