### ISSUE TITLE
Out of the box user onboarding and management

### ISSUE THREAD

**Issue by a-zog** [thedevdojo/auth#59]
**User profile and onboarding management**
Would be great if we have some out of the box components to manage user profile / preferences and team management

**Inspiration**
[Auth0 UI components ](https://components.lab.auth0.com/docs) this would be a good starting point as an inspiration; this would allow for a quick profile editing, user onboarding, organization creation and team invitation out of the box.

Thank you again for your awesome work

**Comment by tnylea** [comment]
Hey @a-zog I think that's a great idea! 

I actually think that this would be good as a separate package that works really well with the Auth Package. We have plans to create a new package `devdojo/profiles` which will seamlessly tie together with DevDojo Auth.

It would probably be a good idea to create an onboarding experience as well, another package that we could create with `devdojo/onboarding`.

We are also working on a version 3.0 of our [SaaS starter kit Wave](https://devdojo.com/wave). The new version will include DevDojo Auth out of the box and we'll be working on the Profiles package soon.

I seen that Auth0 UI components as well and will definitely take inspiration from this 😊

Thanks again and feel free to share any other ideas you have for this package 😉

Hope you have a great day!
