### ISSUE TITLE
Reorder the Social Providers

### ISSUE THREAD

**Issue by bilogic** [thedevdojo/auth#60]
**Is your feature request related to a problem? Please describe.**
Need to promote certain providers over others

**Describe the solution you'd like**
Be able to customize the order of the social providers

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Just want to say, fantastic package!

**Comment by tnylea** [comment]
Thanks @bilogic Appreciate the feedback.

Perhaps in the future we'll have a way to do this via the UI; however, you can simply re-order the way that the social providers show up by changing the order in the devdojo/auth/providers.php config file.

Thanks a ton. Talk to you later.
