### ISSUE TITLE
login error with different social accounts having same email

### ISSUE THREAD

**Issue by BnodpriA** [thedevdojo/auth#61]
**Describe the bug**
When we have already signed in using a social account let's say Facebook having email `username@gmail.com` and again try to log in using a Google account of the same email `username@gmail.com` it breaks the system since the email field is unique.  An exception handle is needed here.

![image](https://github.com/thedevdojo/auth/assets/19488490/65509725-511f-496f-9011-be752c2e8df2)

**Comment by neosign** [comment]
+1 having the same issue

**Comment by bilogic** [comment]
most social providers return a reference, should use that as the key instead.

**Comment by tnylea** [comment]
Just been updated in 1.0.3. You'll now see an error message on the login screen telling the user that they have authenticated with a different provider.

![CleanShot 2024-06-30 at 15 40 53@2x](https://github.com/thedevdojo/auth/assets/601261/6687cc61-7ff7-4e7d-a3a9-92153828c980)

Thanks for letting me know about the issue.
