### ISSUE TITLE
Php artisan make:volt always create a component in devdojo folder

### ISSUE THREAD

**Issue by mfakhrys** [thedevdojo/auth#63]
**Describe the bug**
When you type "php artisan make:volt counter" in the terminal, the component is created inside devdojo/auth/src/../resources/view/pages folder

**To Reproduce**
1. Go to terminal
2. Run php artisan make:volt counter
3. The component created inside devdojo

**Expected behavior**
It should be created inside livewire folder

**Screenshots**
![image](https://github.com/thedevdojo/auth/assets/10110591/45b5908d-a984-49db-a3cd-d18e3a310765)

**System Details**
 - OS: MAC
 - Browser: -
 - Auth Version: 1.0.2

**Additional context**
-

**Comment by tnylea** [comment]
Just added this fix into main. Will be tagging a new release today 👍

**Comment by tnylea** [comment]
Ok, this should be fixed in the latest 1.0.3.

Let me know if you have any other issues. Appreciate it!
