### ISSUE TITLE
Social media buttons content centered

### ISSUE THREAD

**Issue by ckissi** [thedevdojo/auth#65]
**Is your feature request related to a problem? Please describe.**
It would be great to have the ability to center social media button content.

**Additional context**
![CleanShot 2024-06-26 at 15 02 03@2x](https://github.com/thedevdojo/auth/assets/5107590/38f63432-b5f2-4976-9dbc-a4597d9f3afd)

**Comment by tnylea** [comment]
That should be pretty simple to implement. Do you think it should just be added as another option in the Auth Setup Screen?

![CleanShot 2024-06-27 at 11 37 42@2x](https://github.com/thedevdojo/auth/assets/601261/bc5d98c1-3a5e-4a71-ba47-b8a9d0148c52)

Let me know.

Eventually the settings screen will probably need to be re-organized as we add more settings :)

**Comment by ckissi** [comment]
Thanks, Tony!
