### ISSUE TITLE
Registration - confirm password field.

### ISSUE THREAD

**Issue by ckissi** [thedevdojo/auth#66]
**Is your feature request related to a problem? Please describe.**

The option to enable a password confirmation field for registration would be appreciated.

I miss it a lot.

People tend to make mistakes and typos while typing passwords.

**Comment by skdishansachin** [comment]
This sounds like a good enhancement idea. I am working on it and will soon make a PR.

**Comment by tnylea** [comment]
@skdishansachin Sounds awesome! Let me know when you have something I can take a look at, or if you need help implementing anything. If not, I was going to try and implement this myself, but no point in duplicating work. 

Keep me posted 👍

**Comment by skdishansachin** [comment]
@tnylea Sure I will let you know if I need any help along the way. Thank you.

**Comment by tnylea** [comment]
Just merged this into main. I'll be tagging a new release today 🥳

**Comment by ckissi** [comment]
Thank you guys!
