### ISSUE TITLE
Disable basic auth - just keep social providers

### ISSUE THREAD

**Issue by Mgldvd** [thedevdojo/auth#69]
**Describe the solution you'd like**
the option to disable the basic authentication with email and password.
just login with the social providers without having to make a modification to the code.

Once activated, of course, the option to register is also deactivated. #41 

![image](https://github.com/thedevdojo/auth/assets/2009698/fed2e054-ce83-47e4-a382-d3a753e7edfe)

**Comment by tnylea** [comment]
Yeah, so you want to disable user registration via email, correct? I think this is a good idea. So, essentially, you only want users to authenticate via the social provider.

I was thinking that this will be a main setting on the settings page. Where you toggle `disable_registration_via_email`. However, it might be good to still allow users to login with an email and password. After they authenticate via a social network they might be able to go to their profile page and add a password. This would then allow them to login via email and password.

Let me know your thoughts and if that sounds good to you :)

**Comment by scottzirkel** [comment]
In our use case, we would be wanting to have social login only (via company Google account). No passwords, no registration.

**Comment by tnylea** [comment]
I like that. I think that would be a great feature to have. We have this added to the list of things to work on, but let me know if you want to submit a PR and I'll give it a review.

Appreciate it. Closing for now until we get a PR or we work on this feature ourself ;)

https://github.com/orgs/thedevdojo/projects/6/views/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=65672747
