### ISSUE TITLE
Container Alignment not working properly for sign in page

### ISSUE THREAD

**Issue by jerexbambex** [thedevdojo/auth#77]
**Describe the bug**
Container Alignment not working properly for sign in page

**To Reproduce**
1. Go to 'Appearance'
2. Click on 'Alignment'
3. Scroll down to 'Container Alignment'
4. Select any of the left or right alignment image
5. Go to the login page  and see the alignment not showing properly
N.B: it works well for sign up

**Expected behavior**
I expect it to align to the left if I select the left align image, same is true for right alignment image.

**Screenshots**
<img width="2023" alt="image" src="https://github.com/thedevdojo/auth/assets/7734468/53989c02-5e1a-4aa8-8b3c-1906be4a8894">

**System Details**
 - OS: MacOS
 - Browser: chrome
 - Auth Version: 1.0.3

**Additional context**

**Comment by skdishansachin** [comment]
@jerexbambex Got it, thanks for starting the issue. I was able to replicate the problem too. I'm working on it.

**Comment by tnylea** [comment]
Thanks again @skdishansachin. Just published a new release https://github.com/thedevdojo/auth/releases/tag/1.0.4, which should resolve this. 

Thanks a ton!
