### ISSUE TITLE
Google Login Callback Error Because of the Composite Primary Keys

### ISSUE THREAD

**Issue by arbiyanto** [thedevdojo/auth#78]
**Describe the bug**
The `createSocialProvider` function will return an error because Laravel doesn't support composite primary keys defined in the `SocialProviderUser` model. It's related to the [Pull Request](https://github.com/thedevdojo/auth/issues/51).

**To Reproduce**
1. Setup the Google Login Provider
2. Login to Google with an Account not registered in the database yet.
3. The error below will shown

**Expected behavior**
Login successfully without an error.

**Screenshots**
<img width="1338" alt="Screenshot 2024-07-03 at 06 13 01" src="https://github.com/thedevdojo/auth/assets/17454427/0c7c5783-ea44-43df-a154-ea5cbfa1e2bb">
<img width="854" alt="Screenshot 2024-07-03 at 06 13 38" src="https://github.com/thedevdojo/auth/assets/17454427/a599f26c-bda8-4458-bc09-c1462943c388">

**System Details**
 - OS: MacOS Sonoa
 - Browser: Arc Browser (Chromium)
 - Auth Version: 1.0.3
 - Laravel Version: v11.14.0 

**Current Solution**
Simply adding [thiagoprz/eloquent-composite-key](https://github.com/thiagoprz/eloquent-composite-key) package will solve the problem.

```php
use Thiagoprz\CompositeKey\HasCompositeKey;

class SocialProviderUser extends Model
{
    use HasCompositeKey;
    protected $table = 'social_provider_user';
    // Prevents the "returning id" default behaviour
    protected $primaryKey = ['user_id', 'provider_slug'];
```

**Comment by tnylea** [comment]
I've just updated the PR that you opened here: https://github.com/thedevdojo/auth/pull/79 with a video where I'm trying to replicate it. I'm going to close this issue and reference this issue in the PR, this way we can handle all of our conversation from there.

Let me know how I can replicate this on my end and then we can see about getting it merged. Thanks!
