### ISSUE TITLE
Design Bug | None centered login card sits in top corner of view

### ISSUE THREAD

**Issue by Fludem** [thedevdojo/auth#83]
**Describe the bug**
When choosing left align for the container placement (I would presume right aligned also)
the container is placed in the top left/right of the page. 

I'm assuming this is a design issue that just needs quickly fixing. 

The affected div element that doesn't have the h-full class is here:

Main Element > div element with classes relative w-full h-full > Livewire element with classes w-full and relative (missing h-full)

The children of the root element for the livewire component do have h-full (auth-container-parent and auth-container).

**To Reproduce**
1. Go to Settings / Config
2. Change header and container alignment to left
3. See issue on login page

**Expected behavior**
Probably should stretch the livewire element with h-full

**Screenshots**
<img width="1673" alt="image" src="https://github.com/thedevdojo/auth/assets/11637247/fcbd4d4d-6399-4b3a-bc6a-92346dc36772">

**System Details**
 - Auth Version 1.0.3

**Comment by Fludem** [comment]
Related to #77

**Comment by tnylea** [comment]
Just published a new release https://github.com/thedevdojo/auth/releases/tag/1.0.4, which should resolve this. Thanks for opening the issue.

**Comment by Fludem** [comment]
> Just published a new release [`1.0.4` (release)](https://github.com/thedevdojo/auth/releases/tag/1.0.4), which should resolve this. Thanks for opening the issue.

Thank you!
