### ISSUE TITLE
Auth for API's

### ISSUE THREAD

**Issue by michaelsperber** [thedevdojo/auth#87]
I would like to use devdojo/auth as a management tool for API requests, including login, logout, totp registration and validation. It would be a replacement for Laravel Fortify and Sanctum - but with the ease of use of devdojo/auth for handeling features of the application

**Additional context**
My use case is having multiple Vue frontends on a laravel backend, in which laravel provides the API, as a pure data layer. Some users may login through multiple frontends (which provide different role-based functionality). From the frontend I need login and logout but also 2FA: registering the users topt code, and after login checking the users totp. through devdojo/auth we can also provide social accounts, replacing Laravel Socialite.

**Comment by tnylea** [comment]
@michaelsperber Thanks for the suggestion. This may be possible in a future version. 

Please make sure to add this as a suggestion to our Suggestion board here: https://suggest.gg/devdojo-auth/ideas

We're going to start working on ideas that are top priority in this list. Closing for now, but be sure to add this feature suggestion.

Appreciate it! TTYS
