### ISSUE TITLE
Light-Mode/Dark-Mode Background Color

### ISSUE THREAD

**Issue by Kenthanar** [thedevdojo/auth#89]
Hey There, 

Just a little Question, 

will there a Support for Changin the Background-Color behind the Authentication Card depending on the Browser Theme of Dark-Mode Or Light Mode?

**Comment by tnylea** [comment]
@Kenthanar This might be something that we'll explore later on. I'll make sure to note how many times this request comes up so we can bump up the priority.

Appreciate it 😉
